version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_orangehrm
      - MARIADB_DATABASE=bitnami_orangehrm
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  orangehrm:
    image: docker.io/bitnami/orangehrm:4
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - ORANGEHRM_DATABASE_HOST=mariadb
      - ORANGEHRM_DATABASE_PORT_NUMBER=3306
      - ORANGEHRM_DATABASE_USER=bn_orangehrm
      - ORANGEHRM_DATABASE_NAME=bitnami_orangehrm
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'orangehrm_data:/bitnami/orangehrm'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  orangehrm_data:
    driver: local
